apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nv-monitor
  namespace: monitoring
  labels:
    app: nv-monitor
spec:
  selector:
    matchLabels:
      app: nv-monitor
  template:
    metadata:
      labels:
        app: nv-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      hostPID: true
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-GB10
      tolerations:
        - operator: Exists
      containers:
        - name: nv-monitor
          image: quanzhenglong.com/edge/nv-monitor:main
          args: ["-n", "-p", "9101"]
          ports:
            - containerPort: 9101
              name: metrics
              hostPort: 9101
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
